  steps:
  - label: ":hammer: Tests"
    command: ".buildkite/test1.sh"

  - wait

  - label: ":rocket: Package"
    command: "bash .buildkite/test2.sh"
    artifact_paths: "pkg/*"

  - wait

  - label: ":debian: Publish"
    command: ".buildkite/test3.sh"
    branches: "master"

